### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by cibernicola** [Fictiverse/Redream#1]
I am testing it, it looks good and it is very interesting but when I try to use it, nothing happens, I see no errors, no movement. I have installed dotNet6, I am in windows10, the WebUI startup parameters are set, but nothing.
Any idea?
Thanks

**Comment by Fictiverse** [comment]
Did you enabled API in automatic 1111 webui ?

**Comment by cibernicola** [comment]
Yes, my params:
`--allow-code --theme=dark --listen --api --cors-allow-origins=xxxxx:xxxx,xxxxxx,xxxxx,xxxxxxx,xxxxxxxxxxxx,xxxxx,xxxx   --port xxxx --deepdanbooru --xformers --gradio-img2img-tool color-sketch --vae-path "xxxxxxxxxx"`

May be the port, mine is not the standard one, I'll try right now.

**Comment by Fictiverse** [comment]
You changed the port, the API run with the default one. I will add an option to change it.

**Comment by 4lt3r3go** [comment]
> color-sketch
you dont need that anymore, latest update added a sketch with color painting tab.

btw i didnt understood how to install this, anyone?

**Comment by cibernicola** [comment]
> > color-sketch
> 
> you dont need that anymore, latest update added a sketch with color painting tab.
> 
> > May be the port, mine is not the standard one
> 
> wait, how to change the port? i always searched for this (so maybe i can open 2 stabel diffusion at same time in different ports? )
> 
> btw i didnt understood how to install this Redream here, anyone?

`set COMMANDLINE_ARGS= --port your_desired_port_number`

**Comment by 4lt3r3go** [comment]
> how to install this Redream here, anyone?

pleas brother, this repo is missing install informations and how to launch
any idea how to install and launch this?
